spring:
  application:
    name: custom-dns
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true